defmodule SeedFactory.ArgsPatternAlternativeTest do
  use ExUnit.Case, async: true

  defmodule Schema do
    use SeedFactory.Schema

    # :a and :b both declare :create_user with patterns that disagree on
    # :role, and :b has a second route through :tag_user. The plan runs
    # :create_user for :a and :tag_user for :b, whatever the order of the
    # request and whether :use_user plans :create_user before the traits are
    # resolved. :item has no second route for :q, so the request for both
    # traits fails at planning. The :cfg cluster disagrees inside a nested
    # pattern.
    command :create_user do
      param :role, value: :a

      resolve(fn args -> {:ok, %{user: %{role: args.role, tagged: false}}} end)

      produce :user
    end

    command :tag_user do
      param :user, entity: :user

      resolve(fn args -> {:ok, %{user: %{args.user | tagged: true}}} end)

      update :user
    end

    trait :a, :user do
      exec :create_user, args_pattern: %{role: :a}
    end

    trait :b, :user do
      exec :create_user, args_pattern: %{role: :b}
    end

    trait :b, :user do
      exec :tag_user
    end

    command :use_user do
      param :user, entity: :user

      resolve(fn args -> {:ok, %{x: args.user}} end)

      produce :x
    end

    command :create_item do
      param :kind, value: :x

      resolve(fn args -> {:ok, %{item: args.kind}} end)

      produce :item
    end

    trait :p, :item do
      exec :create_item, args_pattern: %{kind: :p}
    end

    trait :q, :item do
      exec :create_item, args_pattern: %{kind: :q}
    end

    command :create_cfg do
      param :opts do
        param :role, value: :x
        param :level, value: 0
      end

      resolve(fn args -> {:ok, %{cfg: args.opts}} end)

      produce :cfg
    end

    command :tag_cfg do
      param :cfg, entity: :cfg

      resolve(fn args -> {:ok, %{cfg: Map.put(args.cfg, :tagged, true)}} end)

      update :cfg
    end

    trait :na, :cfg do
      exec :create_cfg, args_pattern: %{opts: %{role: :a}}
    end

    trait :nb, :cfg do
      exec :create_cfg, args_pattern: %{opts: %{role: :b}}
    end

    trait :nb, :cfg do
      exec :tag_cfg
    end

    trait :nc, :cfg do
      exec :create_cfg, args_pattern: %{opts: %{role: :c}}
    end

    trait :nl, :cfg do
      exec :create_cfg, args_pattern: %{opts: %{level: 2}}
    end

    command :create_acct do
      param :role, value: :x

      resolve(fn args -> {:ok, %{acct: args.role}} end)

      produce :acct
    end

    command :use_acct do
      param :acct, entity: :acct

      resolve(fn args -> {:ok, %{y: args.acct}} end)

      produce :y
    end

    trait :ra, :acct do
      exec :create_acct, args_pattern: %{role: :a}
    end

    trait :rplain, :acct do
      exec :create_acct
    end

    # A pattern against generated args: the search does not know the value a
    # generator returns, so the conflict surfaces once the args are fixed,
    # before anything runs.
    command :update_acct do
      param :acct, entity: :acct
      param :p1, value: :x

      resolve(fn args -> {:ok, %{acct: args.p1}} end)

      update :acct
    end

    trait :gen, :acct do
      exec :update_acct,
        args_match: fn args -> args.p1 == :c end,
        generate_args: fn -> %{p1: :c} end
    end

    trait :pat, :acct do
      exec :update_acct, args_pattern: %{p1: :a}
    end
  end

  use SeedFactory.Test, schema: Schema

  import TraitAssertions

  test "a declaration whose pattern conflicts with the command's fixed args loses to another route",
       context do
    context = produce(context, user: [:a, :b])

    assert_trait(context, :user, [:a, :b])
    assert context.user == %{role: :a, tagged: true}
  end

  test "the order of the request does not matter", context do
    for request <- [[user: [:b, :a]], [:x, user: [:a, :b]], [:x, user: [:b, :a]]] do
      context = produce(context, request)

      assert_trait(context, :user, [:a, :b])
      assert context.user == %{role: :a, tagged: true}
    end
  end

  test "a rider without a pattern rides along", context do
    context = produce(context, [:y, acct: [:ra, :rplain]])

    assert_trait(context, :acct, [:ra, :rplain])
    assert context.acct == :a
  end

  test "a pattern conflicting with generated args is refused once the args are fixed",
       context do
    assert_raise ArgumentError,
                 """
                 Cannot merge arguments generated by traits for command :update_acct.
                   Path: [:p1]
                   Value 1: :c
                   Value 2: :a
                 """,
                 fn -> produce(context, acct: [:gen, :pat]) end
  end

  test "with no other route the conflict fails the plan loudly", context do
    assert_raise SeedFactory.TraitResolutionError,
                 "cannot satisfy trait :q for entity :item (requested trait)\n" <>
                   "- candidate command :create_item already runs with kind: :p for trait :p, " <>
                   "which conflicts with kind: :q",
                 fn -> produce(context, item: [:p, :q]) end
  end

  test "a nested pattern conflicts on the nested key", context do
    tagged = produce(context, cfg: [:na, :nb])

    assert_trait(tagged, :cfg, [:na, :nb])
    assert tagged.cfg == %{role: :a, level: 0, tagged: true}

    assert_raise SeedFactory.TraitResolutionError,
                 "cannot satisfy trait :nc for entity :cfg (requested trait)\n" <>
                   "- candidate command :create_cfg already runs with opts.role: :a for trait :na, " <>
                   "which conflicts with opts.role: :c",
                 fn -> produce(context, cfg: [:na, :nc]) end
  end

  test "nested patterns on different keys merge", context do
    context = produce(context, cfg: [:na, :nl])

    assert_trait(context, :cfg, [:na, :nl])
    assert context.cfg == %{role: :a, level: 2}
  end
end
