name: CI
on: push

jobs:
  test:
    env:
      MIX_ENV: test
    runs-on: ubuntu-latest
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - otp: '28'
            elixir: '1.19'
          - otp: '29'
            elixir: '1.20'
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix coveralls.github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
